import { Stack, router } from "expo-router";
import { Ionicons } from "@expo/vector-icons";
import {
  ScrollView,
  StyleSheet,
  Text,
  TouchableOpacity,
  View,
} from "react-native";

import { useTheme } from "../context/ThemeContext";

export default function Terms() {
  const { colors } = useTheme();

  return (
    <>
      <Stack.Screen
        options={{
          headerShown: false,
        }}
      />

      <View
        style={[
          styles.container,
          {
            backgroundColor: colors.background,
          },
        ]}
      >
        <View
          style={[
            styles.header,
            {
              borderBottomColor: colors.border,
            },
          ]}
        >
          <TouchableOpacity
            activeOpacity={0.7}
            onPress={() => router.back()}
            style={styles.backButton}
          >
            <Ionicons
              name="arrow-back"
              size={23}
              color={colors.text}
            />
          </TouchableOpacity>

          <Text
            style={[
              styles.headerTitle,
              {
                color: colors.text,
              },
            ]}
          >
            Terms of Service
          </Text>

          <View style={styles.headerRight} />
        </View>

        <ScrollView
          showsVerticalScrollIndicator={false}
          contentContainerStyle={styles.content}
        >
          <View
            style={[
              styles.iconContainer,
              {
                backgroundColor: colors.primary,
              },
            ]}
          >
            <Ionicons
              name="document-text-outline"
              size={31}
              color={colors.primaryText}
            />
          </View>

          <Text
            style={[
              styles.title,
              {
                color: colors.text,
              },
            ]}
          >
            Terms of Service
          </Text>

          <Text
            style={[
              styles.subtitle,
              {
                color: colors.textSecondary,
              },
            ]}
          >
            Please read these terms before using TL-On.
          </Text>

          <View style={styles.section}>
            <Text
              style={[
                styles.sectionTitle,
                {
                  color: colors.text,
                },
              ]}
            >
              1. Acceptance of Terms
            </Text>

            <Text
              style={[
                styles.body,
                {
                  color: colors.textSecondary,
                },
              ]}
            >
              By accessing or using TL-On, you agree to
              these Terms of Service. If you do not agree
              with these terms, please do not use the
              application.
            </Text>
          </View>

          <View style={styles.section}>
            <Text
              style={[
                styles.sectionTitle,
                {
                  color: colors.text,
                },
              ]}
            >
              2. Use of TL-On
            </Text>

            <Text
              style={[
                styles.body,
                {
                  color: colors.textSecondary,
                },
              ]}
            >
              TL-On provides AI-powered conversational
              features, tools, and related functionality.
              You agree to use the application only for
              lawful purposes and in accordance with
              applicable laws.
            </Text>
          </View>

          <View style={styles.section}>
            <Text
              style={[
                styles.sectionTitle,
                {
                  color: colors.text,
                },
              ]}
            >
              3. AI-Generated Content
            </Text>

            <Text
              style={[
                styles.body,
                {
                  color: colors.textSecondary,
                },
              ]}
            >
              Responses generated by AI may contain
              inaccuracies, incomplete information, or
              outdated information. You should independently
              verify important information before relying on
              it.
            </Text>

            <Text
              style={[
                styles.body,
                {
                  color: colors.textSecondary,
                  marginTop: 12,
                },
              ]}
            >
              TL-On should not be treated as a substitute
              for professional medical, legal, financial,
              educational, or other professional advice.
            </Text>
          </View>

          <View style={styles.section}>
            <Text
              style={[
                styles.sectionTitle,
                {
                  color: colors.text,
                },
              ]}
            >
              4. User Content
            </Text>

            <Text
              style={[
                styles.body,
                {
                  color: colors.textSecondary,
                },
              ]}
            >
              You are responsible for the content you submit
              to TL-On. Do not submit content that is
              unlawful, harmful, fraudulent, abusive, or
              infringes the rights of others.
            </Text>
          </View>

          <View style={styles.section}>
            <Text
              style={[
                styles.sectionTitle,
                {
                  color: colors.text,
                },
              ]}
            >
              5. Account Security
            </Text>

            <Text
              style={[
                styles.body,
                {
                  color: colors.textSecondary,
                },
              ]}
            >
              You are responsible for maintaining the
              security of your account and device. If you
              enable App Lock, you are responsible for
              maintaining the security of your device's
              authentication methods.
            </Text>
          </View>

          <View style={styles.section}>
            <Text
              style={[
                styles.sectionTitle,
                {
                  color: colors.text,
                },
              ]}
            >
              6. Prohibited Use
            </Text>

            <Text
              style={[
                styles.body,
                {
                  color: colors.textSecondary,
                },
              ]}
            >
              You must not use TL-On to violate applicable
              laws, abuse or harass others, attempt to gain
              unauthorized access to systems, distribute
              malicious software, or interfere with the
              operation of the service.
            </Text>
          </View>

          <View style={styles.section}>
            <Text
              style={[
                styles.sectionTitle,
                {
                  color: colors.text,
                },
              ]}
            >
              7. Availability
            </Text>

            <Text
              style={[
                styles.body,
                {
                  color: colors.textSecondary,
                },
              ]}
            >
              TL-On may occasionally be unavailable due to
              maintenance, technical problems, network
              issues, or changes to third-party services.
              Features may also be changed, suspended, or
              discontinued.
            </Text>
          </View>

          <View style={styles.section}>
            <Text
              style={[
                styles.sectionTitle,
                {
                  color: colors.text,
                },
              ]}
            >
              8. Third-Party Services
            </Text>

            <Text
              style={[
                styles.body,
                {
                  color: colors.textSecondary,
                },
              ]}
            >
              TL-On may rely on third-party services for
              authentication, AI processing, infrastructure,
              analytics, or other functionality. Your use of
              those services may also be subject to their
              respective terms and policies.
            </Text>
          </View>

          <View style={styles.section}>
            <Text
              style={[
                styles.sectionTitle,
                {
                  color: colors.text,
                },
              ]}
            >
              9. Intellectual Property
            </Text>

            <Text
              style={[
                styles.body,
                {
                  color: colors.textSecondary,
                },
              ]}
            >
              The TL-On application, branding, interface,
              design, and related materials are protected by
              applicable intellectual property laws unless
              otherwise stated.
            </Text>
          </View>

          <View style={styles.section}>
            <Text
              style={[
                styles.sectionTitle,
                {
                  color: colors.text,
                },
              ]}
            >
              10. Limitation of Liability
            </Text>

            <Text
              style={[
                styles.body,
                {
                  color: colors.textSecondary,
                },
              ]}
            >
              To the extent permitted by applicable law,
              TL-On and its developers are not responsible
              for losses or damages arising from reliance on
              AI-generated information, service
              interruptions, or misuse of the application.
            </Text>
          </View>

          <View style={styles.section}>
            <Text
              style={[
                styles.sectionTitle,
                {
                  color: colors.text,
                },
              ]}
            >
              11. Changes to These Terms
            </Text>

            <Text
              style={[
                styles.body,
                {
                  color: colors.textSecondary,
                },
              ]}
            >
              These Terms of Service may be updated from
              time to time. Continued use of TL-On after
              changes are published means that you accept the
              updated terms.
            </Text>
          </View>

          <View style={styles.section}>
            <Text
              style={[
                styles.sectionTitle,
                {
                  color: colors.text,
                },
              ]}
            >
              12. Contact
            </Text>

            <Text
              style={[
                styles.body,
                {
                  color: colors.textSecondary,
                },
              ]}
            >
              If you have questions about these Terms of
              Service, please contact TL-On support through
              the Help & Support section of the application.
            </Text>
          </View>

          <View
            style={[
              styles.notice,
              {
                backgroundColor: colors.surface,
                borderColor: colors.border,
              },
            ]}
          >
            <Ionicons
              name="information-circle-outline"
              size={20}
              color={colors.text}
            />

            <Text
              style={[
                styles.noticeText,
                {
                  color: colors.textSecondary,
                },
              ]}
            >
              These terms are intended as general
              application terms and should be reviewed and
              adapted to the actual legal, business, and
              jurisdictional requirements of TL-On before
              public release.
            </Text>
          </View>

          <Text
            style={[
              styles.updated,
              {
                color: colors.textSecondary,
              },
            ]}
          >
            Last updated: September 2026
          </Text>
        </ScrollView>
      </View>
    </>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },

  header: {
    height: 60,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    borderBottomWidth: StyleSheet.hairlineWidth,
  },

  backButton: {
    width: 42,
    height: 42,
    alignItems: "center",
    justifyContent: "center",
  },

  headerRight: {
    width: 42,
  },

  headerTitle: {
    fontSize: 17,
    fontWeight: "700",
  },

  content: {
    paddingHorizontal: 22,
    paddingTop: 32,
    paddingBottom: 50,
  },

  iconContainer: {
    width: 68,
    height: 68,
    borderRadius: 22,
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "center",
    marginBottom: 20,
  },

  title: {
    fontSize: 27,
    fontWeight: "800",
    textAlign: "center",
    letterSpacing: -0.7,
  },

  subtitle: {
    fontSize: 14,
    lineHeight: 21,
    textAlign: "center",
    marginTop: 9,
  },

  section: {
    marginTop: 32,
  },

  sectionTitle: {
    fontSize: 17,
    fontWeight: "700",
    marginBottom: 10,
  },

  body: {
    fontSize: 14,
    lineHeight: 22,
  },

  notice: {
    flexDirection: "row",
    alignItems: "flex-start",
    borderWidth: StyleSheet.hairlineWidth,
    borderRadius: 16,
    padding: 16,
    marginTop: 34,
  },

  noticeText: {
    flex: 1,
    fontSize: 13,
    lineHeight: 20,
    marginLeft: 11,
  },

  updated: {
    fontSize: 11,
    textAlign: "center",
    marginTop: 24,
  },
});